### ISSUE TITLE
how can I get the dataset in this project?

### ISSUE THREAD

**Issue by hlyf-xs** [fperdigon/LVNet#1]
Hello, I'm really intersted in this project, but I can't find the dataset. Can you help me?

**Comment by fperdigon** [comment]
Hi, thanks for your interest.
It seems the Sunnybrook database web page has changed, it seems is possible to get the data from here. I will fix the link on the README.
https://www.cardiacatlas.org/studies/sunnybrook-cardiac-data/

**Comment by hlyf-xs** [comment]
I&nbsp;have&nbsp;got&nbsp;the&nbsp;dataset&nbsp;from&nbsp;your&nbsp;link，but&nbsp;I&nbsp;found&nbsp;that&nbsp;the&nbsp;format&nbsp;of&nbsp;this&nbsp;dataset&nbsp;was&nbsp;different&nbsp;from&nbsp;your’s．eg．It&nbsp;did&nbsp;not&nbsp;contain&nbsp;the&nbsp;Sunnybrook Cardiac MR Database ContoursPart%s(1, 2, 3) or challenge_%s(training, online, validation) files. So I don't know how to map the contours to images.


the new dataset's images file are looked like this:


Can you share your dataset&nbsp; with me? Appreciate your generous.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fperdigon/LVNet"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月9日(星期二) 凌晨2:27
收件人:&nbsp;"fperdigon/LVNet"<LVNet@noreply.github.com&gt;;
抄送:&nbsp;"海浪一方"<2397585063@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [fperdigon/LVNet] how can I get the dataset in this project? (#1)





 
Hi, thanks for your interest.
 It seems the Sunnybrook database web page has changed, it seems is possible to get the data from here. I will fix the link on the README.
 https://www.cardiacatlas.org/studies/sunnybrook-cardiac-data/
